/**
 * Every SQUN_* environment variable name used by the library.
 * No magic strings — all env var access goes through this constant.
 */
export const SQUN_ENV_VARS = {
  // Core
  ENV: "SQUN_ENV",

  // PostgreSQL
  PG_URL:                "SQUN_PG_URL",
  PG_HOST:               "SQUN_PG_HOST",
  PG_PORT:               "SQUN_PG_PORT",
  PG_DATABASE:           "SQUN_PG_DATABASE",
  PG_USER:               "SQUN_PG_USER",
  PG_PASSWORD:           "SQUN_PG_PASSWORD",
  PG_SSL:                "SQUN_PG_SSL",
  PG_TVP_COPY_THRESHOLD: "SQUN_PG_TVP_COPY_THRESHOLD",

  // MySQL
  MYSQL_URL:      "SQUN_MYSQL_URL",
  MYSQL_HOST:     "SQUN_MYSQL_HOST",
  MYSQL_PORT:     "SQUN_MYSQL_PORT",
  MYSQL_DATABASE: "SQUN_MYSQL_DATABASE",
  MYSQL_USER:     "SQUN_MYSQL_USER",
  MYSQL_PASSWORD: "SQUN_MYSQL_PASSWORD",

  // MSSQL
  MSSQL_URL:       "SQUN_MSSQL_URL",
  MSSQL_HOST:      "SQUN_MSSQL_HOST",
  MSSQL_PORT:      "SQUN_MSSQL_PORT",
  MSSQL_DATABASE:  "SQUN_MSSQL_DATABASE",
  MSSQL_USER:      "SQUN_MSSQL_USER",
  MSSQL_PASSWORD:  "SQUN_MSSQL_PASSWORD",
  MSSQL_AUTH_TYPE: "SQUN_MSSQL_AUTH_TYPE",
  MSSQL_DOMAIN:   "SQUN_MSSQL_DOMAIN",
  MSSQL_UPN:      "SQUN_MSSQL_UPN",

  // SQLite
  SQLITE_FILE: "SQUN_SQLITE_FILE",

  // Azure AD (MSSQL cloud)
  AZURE_TENANT_ID:        "SQUN_AZURE_TENANT_ID",
  AZURE_CLIENT_ID:        "SQUN_AZURE_CLIENT_ID",
  AZURE_CLIENT_SECRET:    "SQUN_AZURE_CLIENT_SECRET",
  AZURE_MANAGED_IDENTITY: "SQUN_AZURE_MANAGED_IDENTITY",

  // Pool
  POOL_MIN: "SQUN_POOL_MIN",
  POOL_MAX: "SQUN_POOL_MAX",

  // Timeouts (ms)
  TIMEOUT_QUERY:   "SQUN_TIMEOUT_QUERY",
  TIMEOUT_TX:      "SQUN_TIMEOUT_TX",
  TIMEOUT_CONNECT: "SQUN_TIMEOUT_CONNECT",
  TIMEOUT_ACQUIRE: "SQUN_TIMEOUT_ACQUIRE",

  // Logging
  LOG_LEVEL:        "SQUN_LOG_LEVEL",
  LOG_SLOW_QUERY_MS: "SQUN_LOG_SLOW_QUERY_MS",

  // Query cache
  CACHE_MAX_SIZE:  "SQUN_CACHE_MAX_SIZE",
  CACHE_TTL_MS:    "SQUN_CACHE_TTL_MS",
  CACHE_MAX_AGE_MS: "SQUN_CACHE_MAX_AGE_MS",
  CACHE_REAPER_MS: "SQUN_CACHE_REAPER_MS",

  // Multiple connections
  DEFAULT_CONNECTION: "SQUN_DEFAULT_CONNECTION",
  CONN_PREFIX:        "SQUN_CONN_",
} as const;
